<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PemetaanSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $data = [
            ['pola_uraian' => 'Angsuran Pinjaman%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 24, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Cadangan Aktiva Produktif (CAP)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 25, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Denda%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 26, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Fee (Anggota Keluar)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 27, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Fee Persentase (Profisi) 1%%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 28, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Jasa Piutang%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 30, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Rapat Tahunan (RAT)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 125, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Pemilihan Pengurus%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 31, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pinjaman dari Bank Pembangunan Daerah (BPD)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 32, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Risiko (Re) 0,5%%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 33, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Jasa Simpanan Non-Saham%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 35, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Non-Saham%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 34, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Pokok (SP)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 36, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Sukarela (SS)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 37, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Wajib (SW)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 38, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Wajib Pinjam (SWP)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 39, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana dari Bank%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 9, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana Kesejahteraan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 40, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Tunjangan Pesangon Karyawan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 41, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Uang Pangkal%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 10, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Komputer%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 4, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Mebel%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 5, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Kendaraan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 7, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Gedung%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 6, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Jasa Pinjaman%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 29, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana RAT%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 42, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana Pendampingan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 43, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Penyisihan Pajak SHU%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 44, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Hibah%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 46, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Jasa Simpanan Bank%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 47, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Simpanan Pokok/Simpana Wajib%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 175, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Pemilihan Pengurus%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 172, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Dana-Dana%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 176, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan CAP%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 177, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Biaya Pajak%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 178, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tabungan Pesangon Karyawan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 180, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana SHU tahun lalu%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 171, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'SHU Tahun Sekarang%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 173, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'SHU%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 187, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'PJKR%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 186, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pinjaman Pihak Ke 2%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 181, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pemupukan Modal Tetap%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 179, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Supervisi%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 167, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Insentif%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 166, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Iuran Dana Sehat%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 182, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Sehat%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 174, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Risiko%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 185, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana RAT%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 169, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Pengurus%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 163, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Kesejahteraan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 170, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Karyawan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 165, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Dana%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 162, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Cadangan Likuiditas%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 183, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Cadangan Koperasi%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 184, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Beban yang harus di bayar%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 168, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

            ['pola_uraian' => 'Pendapatan Jasa Deposito%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 48, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Pajak Jasa Non Saham%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 49, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Deposito%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 50, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Lain-lain1%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 35, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan dari Tarik Titipan SHU%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 51, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Fee (BPKB)%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 52, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Tertangguh%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 8, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Kesehatan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 53, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tabungan Hari Tua Karyawan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 54, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Jaminan PJKR%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 55, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Pendidikan%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 164, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana PDK%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 56, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Sosial%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 57, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyusutan Piutang Ragu-ragu%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 20, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Piutang Ragu-ragu%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 19, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Piutang Khusus%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 18, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Piutang Biasa%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 17, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan di BK3D%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 21, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Serta Data%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 23, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

            ['pola_uraian' => 'Simpanan Hasil Usaha%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 58, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Dana Pengelola%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 59, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Modal Tetap%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 11, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Titipan Utang Pajak SHU%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 60, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihhan Modal Simpanan Anggota%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 1, 'id_akun_kredit' => 61, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

            ['pola_uraian' => 'Dana Cadangan RAT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 85, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Administrasi/Pajak Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 118, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Bensin%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 101, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya BPJS%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 122, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Bunga Hutang Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 117, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Gaji Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 88, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya IPTW (Insentif Pekerja Tidak Tetap Wajib)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 93, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Koordinator%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 94, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Lembur%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 102, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Minum%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 95, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Non-Saham%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 103, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Organisasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 87, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pajak Listrik%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 135, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pajak Wi-Fi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 139, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pemilihan Pengawas/Pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 121, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Tunjangan Anak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 90, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Tunjangan Istri%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 89, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Kesejahteraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 126, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Tunjangan Pensiun Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 123, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pinjaman Anggota%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 62, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 73, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Kesejahteraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 84, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 71, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pengawas%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 72, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Sosial%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 75, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Jasa Simpanan Non-Saham%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 69, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Sisa Hasil Usaha (SHU)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 81, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Non-Saham%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 68, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Pokok (SP)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 64, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Sukarela (SS)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 67, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Wajib (SW)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 65, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Simpanan Wajib Pinjam (SWP)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 66, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Titipan Dana RAT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 77, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Modal Tetap%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 30, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pendapatan Lain-lain%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 45, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

            ['pola_uraian' => 'Simpanan di Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 2, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Simpanan Deposito%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 3, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Angsuran Pinjaman ke BPD%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 63, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Titip (SP, SW, SWP, SS)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 70, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pendidikan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 74, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana PDK%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 76, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Risiko%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 78, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pemupukan Modal Tetap%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 79, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana CAP%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 80, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik THT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 82, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Titipan Pajak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 83, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Pendampingan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 86, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'THR (Karyawan)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 91, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Insentif Pengurus & Pengawas%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 92, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penjaga/Kebersihan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 96, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'THR Penjaga%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 97, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Harkop/Besar Nasional%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 98, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Transportasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 99, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Transportasi Rapat%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 100, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Perawatan Inventaris%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 104, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Kalender/Promosi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 105, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Pendidikan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 106, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Perawatan Gedung%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 107, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Dana Sosial%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 108, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Bonus Pencapaian Target%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 109, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Kesejahteraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 110, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Audit Pengawas%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 111, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Supervisi Pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 112, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Insentif Koordinator%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 113, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Syawalan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 114, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Bingkisan Lebaran%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 115, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Seragam%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 116, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pesangon Purna Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 119, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Denda Pajak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 120, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'CAP (Cadangan Aktiva Produktif)%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 124, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyertaan Modal Tetap%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 127, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Proyektor%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 128, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Pendampingan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 129, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyusutan Tertagih%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 130, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Mebel%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 131, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Gedung%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 132, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Kendaraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 133, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris Komputer%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 134, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak PPH%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 136, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak PBB%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 137, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak SHU%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 138, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak Jasa Simpanan Bank%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 140, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pajak Kendaraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 141, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

            ['pola_uraian' => 'Tarik Dana Komisaris%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 142, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Supervisi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 143, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana RAT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 144, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana PJKR%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 145, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Inventaris Bangunan/Gedung%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 12, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Modal Anggota%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 146, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Tempat Pelayanan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 147, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Inventaris%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 148, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyusutan Tertangguh%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 149, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Insentif PP%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 150, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Dana RAT%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 151, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Hutang Pajak%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 152, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pembelian Inventaris Mebel%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 13, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pembelian Inventaris Gedung%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 14, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pembelian Inventaris Komputer%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 15, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Pembelian Inventaris Kendaraan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 16, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Dana Cadangan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 153, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Dana Pengurus%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 154, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Dana Karyawan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 155, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Penyisihan Dana Pendidikan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 156, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Dana Sosial%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 157, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Dana PDK%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 158, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Penyisihan Pajak Pendapatan%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 159, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'SHU Anggota%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 160, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Biaya Administrasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 161, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Tarik Dana Insentif PP%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 151, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Investasi%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 22, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

            ['pola_uraian' => 'Biaya Penyusutan Inventaris Tanah%', 'kategori_jurnal' => 'DUK', 'id_akun_debit' => 188, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],
            ['pola_uraian' => 'Akumulasi Penyusutan Inventaris Tanah%', 'kategori_jurnal' => 'DUM', 'id_akun_debit' => 189, 'id_akun_kredit' => 1, 'prioritas' => 0, 'deskripsi' => '', 'created_at' => $now, 'updated_at' => $now],

        ];
        // Insert data ke database
        $this->db->table('pemetaan_akun')->insertBatch($data);
    }
}

